version: '3.9'
services:
  api:
    build: .
    container_name: sales_api
    hostname: sales_api
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
    networks:
      - sales_api
  mysql:
    image: mysql:5.7
    container_name: sales_api_db
    hostname: sales_api_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - sales_api
  phpmyadmin:
    image: phpmyadmin
    container_name: sales_api_phpmyadmin
    links:
      - mysql:db
    ports:
      - 8080:80
    networks:
      - sales_api
networks:
  sales_api:
    name: sales_api
    driver: bridge
